### ISSUE TITLE
block level scope

### ISSUE THREAD

**Issue by blake41** [learn-co-curriculum/js-scope-readme#4]
is it true ruby has block-level scope?  i'm not sure, never heard that term before

**Comment by pletcher** [comment]
I think it depends on what we mean by "block." If we mean blocks like those used in `Array#each`, then the answer is probably yes -- although we might think of those "blocks" as lambdas (or `Proc`s) instead of the more generic "blocks." (That got a little Seussical.)

But if we mean inside control statements like `if`, `when`, etc. (which I think the term "block-level scope" usually refers to), then Ruby does not have block-level scope.

So I think we should not introduce the term "block-level scope" here.

**Comment by pletcher** [comment]
Fixed in fa789fd
